### ISSUE TITLE
On ubuntu 18.04 it's not creating stylesheet.css

### ISSUE THREAD

**Issue by mingodad** [arc80/plywood#10]
When following the documentation and try to `Building the Documentation` I'm getting this error and the file `stylesheet.css` is not created (maybe libsass version/bug ?):
```
./WebCooker
Error: Invalid CSS after "    background:": expected expression (e.g. 1px, bold), was "#80868b42;"
        on line 255 of ../../../../../repos/plywood/src/web/theme/layout.scss
>>     background: #80868b42;
   ----------------^
```

**Comment by preshing** [comment]
Just reproduced. I guess older libsass don't recognize this color format. Fix on the way.
