### ISSUE TITLE
scanTextFile issues

### ISSUE THREAD

**Issue by kidnewthe** [arc80/plywood#17]
At [https://github.com/arc80/plywood/blob/main/repos/plywood/src/runtime/ply-runtime/io/text/TextFormat.cpp#L76](url)
u32 numBytesAvailable = ins->tryMakeBytesAvailable(4); // returns < 4 only EOF/error *ONLY*

numBytesAvailable may set to 1 when EOF,and on line 79
"DecodeResult decoded = encoding->decodePoint(ins->viewAvailable());"

when "encoding" use UTF16,at [https://github.com/arc80/plywood/blob/main/repos/plywood/src/runtime/ply-runtime/string/TextEncoding.h#L164](url) will return a empty value.

then lead PLY_ASSERT(decoded.numBytes > 0);

**Comment by preshing** [comment]
Good catch. Fix is on the way.
