### ISSUE TITLE
Is there a minimal version with only the text part ?

### ISSUE THREAD

**Issue by SeleDreams** [arc80/plywood#21]
Hi, I've been working on a software and I need to load files that might either be Shift-JIS, either UTF-8 or UTF-16 (we don't know ahead of time) so i've been interested into the library from this article https://preshing.com/20200727/automatically-detecting-text-encodings-in-cpp/

however it seems like plywood is a whole framework rather than a small library so i was wondering if there was a standalone version of the text handler of plywood to be able to just have the encoding detection part of it

**Comment by preshing** [comment]
You can add these two include paths to your own project:

    repos/plywood/src/runtime
    repos/plywood/src/platform

Then `#include <ply-runtime/filesystem/FileSystem.h>` and use what you need.

You'll also have to build a lib to link with using the source files in the `runtime` and `platform` folders. You could do that manually or you can use PlyTool to create a build system to do it. Follow the [Quick Start](https://plywood.arc80.com/docs/QuickStart) guide, then run:

    plytool build --auto runtime

In the future I'll try to make it easier to use Plywood libraries in other projects.
