### ISSUE TITLE
can I install plywood vs2022(win)?

### ISSUE THREAD

**Issue by dangdkhanh** [arc80/plywood#26]
Hi,
I tried changing this in setup but still no success? Does the library support vs2022?
if(PRESET STREQUAL vs2022)
        set(CMAKE_GENERATOR "Visual Studio 17 2022")
        set(CMAKE_GENERATOR_PLATFORM "x64")
    elseif(PRESET STREQUAL vs2022-32)
        set(CMAKE_GENERATOR "Visual Studio 17 2022")
        set(CMAKE_GENERATOR_PLATFORM "Win32")

**Comment by dangdkhanh** [comment]
Hi, 
The error I get when I run the command line is:
Creating library D:/Tool/.../PlyTool/data/build/bootstrap/plytool/build/Debug/plytool.lib and object D:/Tool/.../data/build/bootstrap/plytool/build/Debug/plytool.exp
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(1094,5): error MSB6006: "link.exe" exited with code -1073741819. [D:/Tool/...\data\build\bootstrap\plytool\build\plytool.vcxproj]
CMake Error at Setup.cmake:180 (message):
  Error building PlyTool: 1

**Comment by preshing** [comment]
Hi again,

I just pushed a commit to add vs2022 support. It seems to work well. Please pull the latest changes try again using `-DPRESET=vs2022`. I'll close this issue but feel free to reopen if you continue to have problems.
