### ISSUE TITLE
Assigning a view of a String to itself corrupts the String

### ISSUE THREAD

**Issue by jlaumon** [arc80/plywood#27]
Hi,

I just noticed doing something like:

```c++
String s = "something";
s = s.shortenedBy(1);
```

gets you a dangling pointer inside `s`, because the operator= destroys this before assigning the new value

https://github.com/arc80/plywood/blob/f00ffdd6433f253adfd1397c8e4f0c02e61d0ab1/repos/plywood/src/runtime/ply-runtime/string/String.h#L96-L103

Actually, now that I'm writing this, I see that `Array` does the same (and `Array::append` too, the parameter is a ref that might point inside the array that gets resized 🙊).

Sorry, I feel bad for reporting this without a PR for fixing it 😅

**Comment by preshing** [comment]
Great catch! Will fix soon, thanks.

**Comment by preshing** [comment]
For `Array::append` and `Array::extend`, I decided to disallow passing the Array's own items back into itself.

**Comment by jlaumon** [comment]
Sounds fair enough!

**Comment by jlaumon** [comment]
Thanks a lot for fixing that so fast!
