### ISSUE TITLE
Add documentation to plytool interface

### ISSUE THREAD

**Issue by tiaanl** [arc80/plywood#3]
Currently it is hard to use the `plytool` without reading the documentation, which is also lacking in details about the commands available.

I propose adding documentation in the feedback while using the `plytool` like other cli based tools.  E.g.

```bash
> plytool
Usage: plytool <command> <subcommand> [<arguments>]

Available commands:
folder - Manages folders in the workspace.
generate - Generates/updates the build files.

Arguments:
--verbose - Increase detail of log output.
...
```

This will improve usability of the tool by a lot.

If this is something that makes sense for the future of the tool, I'd be willing to help contribute this feature.

**Comment by preshing** [comment]
That would be great. Since the output could be quite long, I was thinking of separating it into multiple help commands. Sort of like the [Perforce command line](https://www.perforce.com/manuals/v15.1/cmdref/p4_help.html).

    plytool help module
    plytool help folder
    plytool help generate

**Comment by preshing** [comment]
Thanks for the structure. I'm in the process of extending some PlyTool commands and will add proper descriptions after that.
