### ISSUE TITLE
Thread: different arguments in different implementations

### ISSUE THREAD

**Issue by questor** [arc80/plywood#8]
Hi,
is it on purpose that the thread implementation of C++ has a different run-interface than Posix and Win32?
See https://github.com/arc80/plywood/blob/main/repos/plywood/src/runtime/ply-runtime/thread/impl/Thread_Win32.h#L31 and https://github.com/arc80/plywood/blob/main/repos/plywood/src/runtime/ply-runtime/thread/impl/Thread_CPP11.h#L41

btw: thanks for releasing this great framework, I'm currently using it to build higher level software layers...

**Comment by preshing** [comment]
Hi questor,

It's a mistake. `Thread_CPP11` is just out-of-date because I didn't use it in a long time. Did you run into this by forcing `PLY_PREFER_CPP11` to `1` somewhere?

**Comment by questor** [comment]
found it by accident because I look at how the arguments are handled, if you don't need it anymore why not delete it? (I assume Mac and Linux are using Posix-Interface and Windows Win32).

**Comment by preshing** [comment]
I'd actually keep this code in working shape so that Plywood remains configurable in the future (even if it's not so easy to configure right now). About to submit a fix. Thanks for pointing out the issue!
